### ISSUE TITLE
Split unit tests into individual functions

### ISSUE THREAD

**Issue by mshudrak** [google/gcp_scanner#1]
Currently, we have one large [function](https://github.com/google/gcp_scanner/blob/main/test_unit.py#L67) to unit test all resource crawlers. We need to split it into individual test functions to have more visibility over tests if one failed.

**Comment by sudiptob2** [comment]
Is this issue still exist? Seems refactoring `test_unit` will also solve #14 
I have made this PR #33  regarding this.

**Comment by mshudrak** [comment]
Yep, makes sense. Closing this now.
