### ISSUE TITLE
crawl other GCP services - cloud run

### ISSUE THREAD

**Issue by grumpyp** [google/gcp_scanner#121]
Hi, are there any other GCP services you want to crawl? Like `Cloud Run` for example? Is there any mandatoray checks I need to do before including? 

Couldn't find any roadmap or something so I would just start with that.

**Comment by mshudrak** [comment]
Hi, you can take a look at other already merged PRs to understand what's needed for that. Look at #111 or #40 for examples.

**Comment by grumpyp** [comment]
Hi, thanks for the answer. It's not about the understanding but more of the need. I though there is a roadmap or something.

Cheers
