### ISSUE TITLE
🔖 Add the `version tag` badge in the `README.md`

### ISSUE THREAD

**Issue by peb-peb** [google/gcp_scanner#124]
Since the first version of the tool was released yesterday :partying_face:. Should we add a custom gcp scanner version badge?

If **YES**, then for anyone working on the issue can refer [this](https://github.com/Naereen/badges).

Also, @mshudrak please add the `good first issue` label to it.

**Comment by EmperialX** [comment]
dear mentors , I came across this issue and I would like to work on it. i would appreciate your guidance as I work on this issue. Let me know if you have any suggestions or guidance on how I can get started. can you assign me with more details.
