### ISSUE TITLE
📝 Remove Background for GCP Scanner LOGO

### ISSUE THREAD

**Issue by peb-peb** [google/gcp_scanner#138]
Since the background of the LOGO is white, so in the `dark` theme of GitHub it is visible as 
![image](https://user-images.githubusercontent.com/77539004/230741641-f8b491ad-753d-4d06-9d38-9c95a9ae59d5.png)

So, to solve this issue, the individual should remove the background for the image. 

_**NOTE:**_ They could use https://www.remove.bg/ this website to remove the background.

**Comment by peb-peb** [comment]
@mshudrak please assign this as `good first issue` to this.

**Comment by mshudrak** [comment]
Hm, that's still white for me.

<img width="606" alt="Screenshot 2023-04-10 at 1 54 24 PM" src="https://user-images.githubusercontent.com/69989229/230997060-ce414ceb-aef7-420e-b769-50aad846a582.png">

**Comment by ro4i7** [comment]
@mshudrak We can close this now. 🙂
