### ISSUE TITLE
Do not stop if one unit test fails

### ISSUE THREAD

**Issue by mshudrak** [google/gcp_scanner#14]
Currently, our unit test process stops as soon as one test fails thereby making it hard to evaluate what else breaking without actually fixing the error and relaunching test again. We need to first run all tests and then print summary of failed functions.

**Comment by Pavan-Nambi** [comment]
hey is this  issue still exists? if so can i work on this?

**Comment by mshudrak** [comment]
Oh yes, the issue still exist. Feel free to work on it. I was actually referring to this one: https://github.com/google/gcp_scanner/blob/main/src/gcp_scanner/test_unit.py. It fails as soon as the first assert is not satisfied. I'd use `unittest.mock` module to keep consistency.

**Comment by Pavan-Nambi** [comment]
oo ok gotcha

**Comment by jatinagwal** [comment]
@Pavan-Nambi Can I pick this up?

**Comment by Pavan-Nambi** [comment]
hey @jatinagwal  yeah feel free to do so , i got into some work so wasn't able to do , appologies for delay

**Comment by sudiptob2** [comment]
I am also interested in this issue if it's open.

**Comment by sudiptob2** [comment]
@mshudrak I think its best practice to write single assert per test function. If you agree, I can take on the issue and refactor the tests.
I am looking forward to your opinion 🙂
