### ISSUE TITLE
Too many dead pull request and issues in the project, laying around everywhere.

### ISSUE THREAD

**Issue by Bhardwaj-Himanshu** [google/gcp_scanner#144]
**Is your feature request related to a problem? Please describe.**
There are various pull requests and issues which have not been responded to in quite some time, which could hamper the process of adding features or enhancements to the project, in total hindering the progress of project.

**Describe the solution you'd like**
A workflow or a bot additon, that pings unattended or dead pull requests when they have been not addressed after a particular period of time, mainly 2 weeks.
- [x] Bot then pings both the author and assignee of the issue to get back to issue, unable of doing which after a cool down time closes the issue or PR.

**Describe alternatives you've considered**
Alternatives could be a person monitoring this, which is not possible.

**Additional context**
None

**Comment by ZetaTwo** [comment]
Thanks for the suggestion. We don't have a large volume on the project and it is absolutely sufficient to handle PR and issues manually for now. If this changes in the future we can reconsider this.

**Comment by Bhardwaj-Himanshu** [comment]
I do agree with you @ZetaTwo, but if you and other contributors permit, could I try making one? I know there is no need, but adding new features at the time of a bigger project could cause more breakage than now.

Also, I would be happy to work on this as a side project?
Thanks!

**Comment by ZetaTwo** [comment]
You are welcome to build a bot on your own and test it on your own test project but we don't need to add it to this project currently.
