### ISSUE TITLE
Avoid using %s/%d in print and logging.info

### ISSUE THREAD

**Issue by mshudrak** [google/gcp_scanner#16]
We have several places where we use %s or %d formatting in order to print data. We should use new [PEP3101](https://peps.python.org/pep-3101/) guide and rely on string formatting in order to perform string formatting and printing.

**Comment by worldworm** [comment]
> Although https://github.com/google/gcp_scanner/issues/16, I still used the string formatting. My understanding is that this is best practice in combination with logging:
> 
> - https://docs.python.org/3/howto/logging.html#optimization
> - https://pylint.pycqa.org/en/latest/user_guide/messages/warning/logging-format-interpolation.html
> - https://pylint.pycqa.org/en/latest/user_guide/messages/warning/logging-fstring-interpolation.html

**Comment by ZetaTwo** [comment]
Is this really the way to go for logging? I've always thought that letting the logging framework perform the string interpolation is preferred since in theory it allows for various types of analysis and transforms at the logging stage.

**Comment by ArkaprabhaChakraborty** [comment]
Well, My PRs CI failed 
Reason:
```
Use lazy % formatting in logging functions (logging-format-interpolation)
```

**Comment by ArkaprabhaChakraborty** [comment]
So I guess we do not move forward with the logging changes :). Can be terribly wrong tho :)

**Comment by ZetaTwo** [comment]
Yeah that CI message is how how I've always learned it so I would say close this issue and the PR but I'll let @mshudrak have the final say.

**Comment by mshudrak** [comment]
Yea sorry about that @ArkaprabhaChakraborty. It seems like I was wrong about the string formatting guidance :( we can close the issue and PR.
