### ISSUE TITLE
Implement Cloud Source Repositories API crawler

### ISSUE THREAD

**Issue by mshudrak** [google/gcp_scanner#19]
[Cloud Source Repositories](https://cloud.google.com/source-repositories/docs/reference/rest/v1/projects.repos/list) allows to query list of repos per project. We need to implement a scanner capable of querying list of projects.

**Comment by PradyumnaKrishna** [comment]
Hey @mshudrak, I would like to work on this issue. Please assign this to me.

**Comment by mshudrak** [comment]
Thanks, done.
