### ISSUE TITLE
Add support of OAuth2 credentials with no scopes provided

### ISSUE THREAD

**Issue by mshudrak** [google/gcp_scanner#21]
Currently, user needs to provide valid scopes for OAuth2 refresh token along with client_id and client_secret. However, it is not necessary and can be done with no scopes specified at all. We need to support that.

**Comment by mshudrak** [comment]
Thanks, assigning this one to you.

**Comment by ArkaprabhaChakraborty** [comment]
Okay, I do need some starters on how to go about this one. Probably it will be some modification in credsdb.py? Can be wrong tho.

**Comment by ArkaprabhaChakraborty** [comment]
@mshudrak am I on th right track?

**Comment by mshudrak** [comment]
So, that's not a simple issue but I'd encourage you to play with OAuth2 to understand how refresh token is exchanged for access token and how it is related to scopes. The code where we actually set scopes is located [here](https://github.com/google/gcp_scanner/blob/main/src/gcp_scanner/credsdb.py#L343). As you can see, if user provided refresh token with no scopes we assume user wants `cloud-platform` which is not always right. It is actually possible to exchange refresh token for access token without specifying scopes.

**Comment by mshudrak** [comment]
We have a lot of interest from other members of community. So, I will drop assignees for all bugs, so anyone can work on them.
