### ISSUE TITLE
Include commit message and branch naming convensions in the `contributing.md`

### ISSUE THREAD

**Issue by sudiptob2** [google/gcp_scanner#24]
Currently, our `contributing.md` document lacks a branch naming convention and example commit messages. 

This document plays a crucial role in maintaining a cohesive structure throughout the project and will greatly aid new contributors in familiarizing themselves with the project. Therefore, we need to incorporate standardized **commit message formats** and **branch naming conventions** in accordance with established community best practices.

**Comment by rudrakshkarpe** [comment]
As this issue suggests I have improved ```contributing.md``` with some standard naming conventions for commits as well as branches. I tried providing some examples with it as well, if you find some improvements please let me know, I'd be happy to improve with PR #43 :)

**Comment by mshudrak** [comment]
Can we close this one?

**Comment by sudiptob2** [comment]
I think so, there are still some typos though in the `contributing.md`. I think eventually we can create other issues for that.
