### ISSUE TITLE
But Report

### ISSUE THREAD

**Issue by sbnewsthailand** [google/gcp_scanner#243]
Your issue may already be reported! Please search on the [issue tracker](https://github.com/google/gcp_scanner/issues) before creating a new one.

**Affected Component**

* [x] Crawl
* [x] CredsDB
* [x] Scanner
* [x] Test
* [x] Docs
* [x] Python
* [x] GCP APIs

**Describe the bug**

**To Reproduce**

1. Set the credentials to'...'
2. Update the scope to '....'
3. Run the command `gcp-scanner ....`
4. See the output JSON line no ....

**Expected behavior**

**Current behavior**

**Screenshots**

**Additional context**

**Comment by sbnewsthailand** [comment]
> Your issue may already be reported! Please search on the [issue tracker](https://github.com/google/gcp_scanner/issues) before creating a new one.
> 
> **Affected Component**
> 
>     * [x]  Crawl
> 
>     * [x]  CredsDB
> 
>     * [x]  Scanner
> 
>     * [x]  Test
> 
>     * [x]  Docs
> 
>     * [x]  Python
> 
>     * [x]  GCP APIs
> 
> 
> **Describe the bug**
> 
> **To Reproduce**
> 
> Steps to reproduce the behavior:
> 
>     1. Set the credentials to'...'
> 
>     2. Update the scope to '....'
> 
>     3. Run the command `gcp-scanner ....`
> 
>     4. See the output JSON line no ....
> 
> 
> **Expected behavior**
> 
> **Current behavior**
> 
> **Screenshots**
> 
> **Additional context**

**Comment by ZetaTwo** [comment]
Please update the issue with some actual content
