### ISSUE TITLE
Include a pull request template

### ISSUE THREAD

**Issue by sudiptob2** [google/gcp_scanner#25]
Including a [GitHub pull request template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) can be a fantastic way to ensure a consistent structure is maintained when creating a Pull Request. Additionally, it can provide a checklist for new contributors to follow when submitting a **PR**.

**Comment by aswin2108** [comment]
@mshudrak @sudiptob2 Can I work on this?

**Comment by sudiptob2** [comment]
Create a PR if you think you can give it a shot. I can review the PR and help you if @mshudrak agrees.

**Comment by rudrakshkarpe** [comment]
I have created a standard pull request template to help contributors create high-quality pull requests. The new template includes prompts for sections on the problem description, proposed solution, and validation steps.

You can find the pull request with the new template here #42 

Please review my PR and let me know if you have any feedback or suggestions. I hope that this new template will make it easier for us to collaborate effectively on this project. Thank you!
