### ISSUE TITLE
Bug: bigquery crawler replaces data instade of appending to the list

### ISSUE THREAD

**Issue by sudiptob2** [google/gcp_scanner#254]
The existing implementation of bigquery crawler replaces the crawl data to the result array instead of appending the data when the response in paginated.

Ref: [source code](https://github.com/google/gcp_scanner/blob/3c3023fb3ca657e05421df610eb78b90609fc649/src/gcp_scanner/crawler/bigquery_crawler.py#L78C9-L78C23)

**Comment by mshudrak** [comment]
Nice catch! Thanks for reporting that.
