### ISSUE TITLE
Visualization Tool: Search using regex

### ISSUE THREAD

**Issue by yahia3200** [google/gcp_scanner#276]
The user can search through the scanned resources using their names and IAM policy roles with emails.
So one improvement is to implement another search mode where the user can search using a regex expr through resource names and other text attributes for resource.

**Comment by aryanagrawal22** [comment]
Hey, do we want a separate button to enable the regex search in the search box, or something like if the search box has a valid regex expr then we find results accordingly?

**Comment by mshudrak** [comment]
yep, the second option sounds reasonable for me. No need for a separate button. Thanks for chiming in on this bug.

**Comment by aryanagrawal22** [comment]
Understood, I have made the relevant changes and raised a PR: https://github.com/google/gcp_scanner/pull/301. Please let me know if any changes are required.
