### ISSUE TITLE
Visualization Tool: Add a table view for resources page

### ISSUE THREAD

**Issue by yahia3200** [google/gcp_scanner#278]
Add an option for the user to show parsed resources in a more compact view like a table for example. This can be useful for projects with a lot of resources and for quick insights

**Comment by aryanagrawal22** [comment]
Hello, I want to start working on this issue. Can I be assigned to it.
Also, just to be on the same page. We are talking about some sort of a toggle button which can switch between current(tiled) view and the new compressed table view?

**Comment by mshudrak** [comment]
Hi, thanks for your interest. We are not assigning issues. If you are interested just submit PR with the change and we will take a look.

We can start with a toggle button, I think.

**Comment by aryanagrawal22** [comment]
Heya, I have made the relevant changes, does this looks good enough to resolve the issue?

Demo:
![](https://media.giphy.com/media/Jybe2Zi1PnZxxvjtcp/giphy.gif)

**Comment by aryanagrawal22** [comment]
I have raised a PR https://github.com/google/gcp_scanner/pull/300 for this issue
