### ISSUE TITLE
Visualization Tool: Reduce number of steps to upload a file

### ISSUE THREAD

**Issue by yahia3200** [google/gcp_scanner#279]
Instead of the current flow where the user chooses the file and then presses the plus icon to add the file, the file should be added without need for extra step

**Comment by adityakushwaha12** [comment]
I want to work on this issue.

**Comment by yahia3200** [comment]
Thank you for your interest in contributing, but a fix for this issue will be merged soon.
 
If you are interested in contributing to the gcp scanner visualizer, I would recommend working on #278 or #276
