### ISSUE TITLE
Make scanner parallel

### ISSUE THREAD

**Issue by mshudrak** [google/gcp_scanner#3]
We need to crawl GCP resources in parallel to improve performance of the scanner.

**Comment by ph1ne4s** [comment]
Hii, I am interested in working on this issue. Could you give a brief on what could be done for parallelization?

**Comment by mshudrak** [comment]
Hi, well, this is quite large issue. I'd suggest working on something minor first. This issue is part of GSoC idea 2 [here](https://github.com/google/gcp_scanner/wiki/Google-Summer-of-Code-2023#2-parallelization).

**Comment by ro4i7** [comment]
Hello @mshudrak 
i think here, we can use the `concurrent.futures` module in Python's standard library.

**Comment by mshudrak** [comment]
@ro4i7, yes this is one of the potential solutions here.

**Comment by ro4i7** [comment]
@mshudrak @ZetaTwo please check #106

**Comment by AwesomeSauce42** [comment]
Hi, I would like to work on this issue. I thought we could implement a parallel scanning and enumeration framework to distribute workloads across multiple threads or processes. This can be achieved using libraries such as multiprocessing or asyncio.

**Comment by EmperialX** [comment]
Hello @mshudrak  , I came across this project  and I would like to work on fixing it and would appreciate your guidance as I work on this project. Let me know if you have any suggestions. can you help me on this.

**Comment by mshudrak** [comment]
@EmperialX it is a part of GSoC 2023 ideas which require a lot of work with mentors. Feel free to propose changes but you likely need a proposal to implement this feature
