### ISSUE TITLE
Command to activate virtual environment on windows is wrong

### ISSUE THREAD

**Issue by dhruvpal05** [google/gcp_scanner#309]
**Affected Component**

* [ ] Crawl
* [ ] CredsDB
* [ ] Scanner
* [ ] Test
* [ .] Docs
* [ ] Python
* [ ] GCP APIs

**Describe the bug**

In `INSTALL.md` , in the section Build from source step 4. Activate the Virtual Environment with, on windows section `.\venv\Scripts\activate.bat` this command should not include `.bat` as `.\venv\Scripts\activate\` this is the correct command for activating virtual environment on windows.

**To Reproduce**
On windows execute the command `.\venv\Scripts\activate.bat`  after creating the virtual environment, it will not activate the virtual environment.
Instead `.\venv\Scripts\activate` this will activate the virtual environment.

**Expected behavior**

It should activate the virtual environment.

**Current behavior**

It does noting, and does not activate the virtual environment.

**Screenshots**

![Screenshot (403)](https://github.com/google/gcp_scanner/assets/91111849/3a0926ee-66a1-469e-beeb-d10c04fab05f)

As we can see nothing happens above 

![Screenshot (404)](https://github.com/google/gcp_scanner/assets/91111849/4c5aa698-b149-4dda-a275-7780f7e65b96)

Here this command activates the virtual environment.

**Additional context**

I can create a PR right away for this issue, if someone can review this issue and verify.

**Comment by mshudrak** [comment]
Hey @dhruvpal05, thanks for pointing out. Please submit PR and I will make sure to review it.

**Comment by dhruvpal05** [comment]
Hey @mshudrak , make a PR #310 please review . Thank you
