### ISSUE TITLE
Add Code Style Rules

### ISSUE THREAD

**Issue by ZhengLin-Li** [google/gcp_scanner#48]
When I opened this project in Pycharm, it showed that there was a code-style problem.

![image](https://user-images.githubusercontent.com/63448884/221331937-c0a8f270-568b-4afe-b71f-331ed6a2964e.png)

However, I did not find code-style rules in https://github.com/google/gcp_scanner/blob/main/CONTRIBUTING.md. Maybe we should add it.

**Comment by mshudrak** [comment]
Thanks for flagging. We follow [Google Python Code Style Guideline](https://google.github.io/styleguide/pyguide.html) and launch pylint with [pylintrc](https://google.github.io/styleguide/pylintrc). PTAL for more details https://github.com/google/gcp_scanner/wiki/GCP-Scanner-Development-and-Testing
