### ISSUE TITLE
bug: small  typo

### ISSUE THREAD

**Issue by ZhengLin-Li** [google/gcp_scanner#61]
what the problem is:
`pyinstaller -F --add-data 'roots.pem:grpc/_cython/_credentials/" scanner.py` should be `pyinstaller -F --add-data 'roots.pem:grpc/_cython/_credentials/' scanner.py`

what we should do:
```diff
- pyinstaller -F --add-data 'roots.pem:grpc/_cython/_credentials/" scanner.py
+ pyinstaller -F --add-data 'roots.pem:grpc/_cython/_credentials/' scanner.py
```

where the problem is: https://github.com/google/gcp_scanner/blob/103cbd0cbad74ceff8aa04b891351cbf41f71886/README.md#L92

**Comment by ggold7046** [comment]
Hi @ZhengLin-Li  , there is a pull request https://github.com/google/gcp_scanner/pull/50 which is for the readme.md file opened  by me. I have corrected this typo.
