### ISSUE TITLE
bug: .github directory does not support PR_TEMPLATE aggregation

### ISSUE THREAD

**Issue by sudiptob2** [google/gcp_scanner#72]
Due to the #66, it created a bug. Actually .github folder does not support PR_TEMPLATE aggregation. Hence the due to the PR #67, now we don't see PR template while creating a PR.

DOD
- move `pull_request_template.md` to the `.github/pull_request_template.md`
- remove the PR_TEMPLATE folder

**Comment by aryanagrawal22** [comment]
So basically we have to move pull_request_template.md from inside the directory to .github folder and delete the PR_TEMPLATE folder? 
**Please assign me this issue. I want to fix the bug**
