### ISSUE TITLE
fomatting error in the `contributing.md`

### ISSUE THREAD

**Issue by sudiptob2** [google/gcp_scanner#78]
There is a formatting error in the `contributing.md`. This following line is not rendered correctly.

(Example: feat//gcp-compute-engine-support) 

DOD
- mark the line as code to fix the error. for example, change Example: feat//gcp-compute-engine-support -> Example: `feat/<issue-id>/gcp-compute-engine-support`

**Comment by aryanagrawal22** [comment]
**Please assign me this issue.** Really happy to get a chance to contribute.
