### ISSUE TITLE
BUG: Output is appended for each scan on a single project

### ISSUE THREAD

**Issue by peb-peb** [google/gcp_scanner#79]
**Current behavior** -> The output is appended to the same JSON file every time we scan the same SA. 

maybe we could try the following:

- [ ] generate output files for each scan based on the time of the scan <-- (As discussed in the mail, this should be the way to approach this issue)
~~add a scan number/time of scan in the JSON itself.~~

For reference, I am running the following command multiple times-
`gcp-scanner -l INFO -o output -k /home/peb/Downloads`

**Comment by Am0stafa** [comment]
Hello @peb-peb! I came across an interesting problem that I'd like to tackle. Would it be possible to assign me to this issue? I believe with some guidance and support, I'll be able to make meaningful progress and work towards a solution. Thank you for considering my request!

**Comment by Am0stafa** [comment]
Hi @peb-peb! I'm interested in tackling this issue and I think I have the necessary skills to make a contribution. Would it be possible to assign this issue to me? I believe with some guidance and support, I'll be able to make meaningful progress and work towards a solution. Thank you for considering my request!

**Comment by peb-peb** [comment]
Also, I'm also working around this on my local machine, so if you need any assistance, be sure to tag me :)

**Comment by 3V3RYONE** [comment]
Hello @Am0stafa and @peb-peb, I was actually working on this issue since past two days and I have made the PR now. Sorry to not let you know earlier. I really do not want to stop you from working on this issue. Feel free to add any changes/commits in my PR as a collaborator if you wish to. 

Hope you do not mind it. Thank you :)

**Comment by Am0stafa** [comment]
Actual the reason I asked to get assigned is that i don't work on something someone else is working on, I'm completely new to open source usually i do solo projects or work on with a team on a project but the way i see it is someone gets assigned an issue for 2-3 days and if nothing is reached someone else gets assigned.

**Comment by Am0stafa** [comment]
but overall @3V3RYONE solution was great and I learned from it and that's actually the goal is to learn either from my solution or someone else's solution and I believe that there is no competition and that we all are working toward the same goal which is making this project better

**Comment by peb-peb** [comment]
@mshudrak I'd like to work on this issue if the current PR is no longer being actively worked on. Should I move forward with this?

**Comment by 3V3RYONE** [comment]
Just got a bit caught up with semester examinations. Will do the required work within a day

**Comment by peb-peb** [comment]
Ok! No problem :)
