### ISSUE TITLE
Style: code format problem

### ISSUE THREAD

**Issue by ZhengLin-Li** [google/gcp_scanner#82]
I am using PyCharm to develop our project. I am confused about how to let PyCharm format code in our convention. It seems that our community uses 2 incidents, but PyCharm always lets me format it to 4 incidents. 

How can I solve this? Is there a style file I can import into my PyCharm?

![image](https://user-images.githubusercontent.com/63448884/223407612-29177d87-620c-4ec4-af1d-bdaa09893165.png)

**Comment by ZhengLin-Li** [comment]
@peb-peb hi, could you have a loock on #85 ? I set the incident to 2 in PyCharm and format our project. Is that kinds of code style we are looking?

**Comment by mshudrak** [comment]
Here you can find [pylintrc](https://google.github.io/styleguide/pylintrc) that we use in our test environment. Probably you can load that file in PyCharm.

**Comment by ro4i7** [comment]
Hello @mshudrak @ZhengLin-Li 
I think to solve this issue we can configure the code style settings in PyCharm to match the coding convention used by the community. By following the steps we can do it: 

1. Open PyCharm and go to File -> Settings (or PyCharm -> Preferences on Mac).
2. In the left-hand pane, click on "Editor" and then click on "Code Style".
3. In the right-hand pane, we should see a list of programming languages that PyCharm supports. Select the language that we are working with (e.g., Python) and click on it.
4. We should now see a tab for "Tabs and Indents". Click on it and we should see an option for "Tab size" and "Indent".
5. Change the "Tab size" to 2 and "Indent" to 2 as well.
6. Click "OK" to save the changes.

After configuring the code style settings, PyCharm will automatically format the code according to the community's convention of 2 spaces per indent. 

If we want to make sure that our code is formatted correctly, we can use the "Reformat Code" option in PyCharm to reformat the code in our file.
