### ISSUE TITLE
Publish gcp scanner to PyPI using github actions.

### ISSUE THREAD

**Issue by sudiptob2** [google/gcp_scanner#89]
**Is your feature request related to a problem? Please describe.**
Currently, GCP scanner is not published in PyPI. Publishing it in PyPI will give the project more visibility as well as the flexibility to download the application. Also, it will provide better SEO (Search engine optimization)

**Describe the solution you'd like**

- [x] Prepare `pyproject.toml` 
- [x] Prepare project in PyPI
- [x] Implement release versioning using GitHub tag.
- [x] A GitHub action
     - On the creation of release in GitHub it should trigger an action to publish it PyPI also.

Please suggest if you have any other improvements.

**Comment by sudiptob2** [comment]
@mxmssh @ZetaTwo please suggest if you have anything else in mind. Also I think for this issue, you can assign it to me :slightly_smiling_face:

**Comment by sudiptob2** [comment]
@mxmssh @ZetaTwo please suggest if you have anything else in mind. Also I think for this issue, you can assign it to me :slightly_smiling_face:

**Comment by mshudrak** [comment]
Currently, Github actions are not triggered. We need to first implement release process (see #20) in order to make this work.

**Comment by mshudrak** [comment]
We may also want to publish in test PyPI first and then make it to production. https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

**Comment by sudiptob2** [comment]
I can work on a test action I you suggest, this is the test package https://test.pypi.org/project/gcp-scanner/

**Comment by opencontri** [comment]
Is this issue assigned to somone?

**Comment by sudiptob2** [comment]
@opencontri, I am currently working on this issue, Basically, this issue is done and merged. However, it has a dependency on #20 that's why we are not closing it.

**Comment by opencontri** [comment]
Got it, is there any issue I can work upon?
